# Generated by Django 3.0.7 on 2020-06-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='docent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Professor'),
        ),
        migrations.AddField(
            model_name='exam',
            name='participants',
            field=models.ManyToManyField(to='university.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Exam'),
        ),
        migrations.AddField(
            model_name='grade',
            name='result',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Student'),
        ),
        migrations.AddField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='matriculation_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
