# Generated by Django 3.0.7 on 2021-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_auto_20210108_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams', models.ManyToManyField(to='university.Exam')),
                ('professors', models.ManyToManyField(to='university.Professor')),
                ('students', models.ManyToManyField(to='university.Student')),
            ],
        ),
    ]
