# Generated by Django 3.0.7 on 2021-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_indexs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexs',
            name='exams',
        ),
        migrations.AddField(
            model_name='indexs',
            name='exams',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='indexs',
            name='professors',
        ),
        migrations.AddField(
            model_name='indexs',
            name='professors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='indexs',
            name='students',
        ),
        migrations.AddField(
            model_name='indexs',
            name='students',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
