# Generated by Django 3.0.7 on 2021-01-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20210108_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indexs',
        ),
    ]
