# Generated by Django 3.0.7 on 2021-01-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_delete_indexs'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exams_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Exam')),
                ('professors_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Professor')),
                ('students_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Student')),
            ],
        ),
    ]
