# Generated by Django 3.0.7 on 2021-01-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_indexs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexs',
            name='exams_name',
        ),
        migrations.AddField(
            model_name='indexs',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='indexs',
            name='professors_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='indexs',
            name='students_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
