# Generated by Django 3.0.7 on 2021-01-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20210109_0514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='indexs',
        ),
    ]
